### ISSUE TITLE
What does the "Add Timestamp" keybind do?

### ISSUE THREAD

**Issue by liuandi233** [Alexdoru/MegaWallsEnhancements#11]
title

**Comment by Alexdoru** [comment]
When you press it, it saves the serverID you are in, the time and the time since the game started. Basically all the informations needed by a moderator to uniquely identify a replay and a timestamp in that replay. Then you can use that timestamp to fill a cheating report for a player. That was used before game master existed when we could personally message moderators and ask them to look at a certain replay for a player cheating.

**Comment by liuandi233** [comment]
> When you press it, it saves the serverID you are in, the time and the time since the game started. Basically all the informations needed by a moderator to uniquely identify a replay and a timestamp in that replay. Then you can use that timestamp to fill a cheating report for a player. That was used before game master existed when we could personally message moderators and ask them to look at a certain replay for a player cheating.

so where can I that saved infomation? is it on my clipboard or saved to a file

**Comment by Alexdoru** [comment]
When you press the keybind, it prints a message in the chat and if you put your mouse over the message, it’ll tell you the information

**Comment by liuandi233** [comment]
oh thats pretty hidden
